In [1]:
import numpy as np

In [2]:
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
x = np.random.rand(5)
print(x)

[0.41854603 0.10614605 0.56710468 0.3346986  0.73904987]


In [4]:
x = np.array([10, 20, 30])
y = np.array([40, 50, 60, 70, 80, 90])

z = np.append(x, y)


print(z)

[10 20 30 40 50 60 70 80 90]
