In [18]:
import math
import numpy as np
import random

nums = list(random.sample(range(2, 100), 15))
print(nums)


rounded_numbers = [round(num) for num in nums]

# Print the rounded numbers
print("Rounded numbers:", rounded_numbers)

# Print the square root of each number in the list
print("Square roots:")
for num in nums:
    sqrt = math.sqrt(num)
    print(f"The square root of {num} is {sqrt:.2f}")


[15, 99, 61, 23, 21, 22, 75, 80, 28, 3, 33, 4, 81, 92, 43]
Rounded numbers: [15, 99, 61, 23, 21, 22, 75, 80, 28, 3, 33, 4, 81, 92, 43]
Square roots:
The square root of 15 is 3.87
The square root of 99 is 9.95
The square root of 61 is 7.81
The square root of 23 is 4.80
The square root of 21 is 4.58
The square root of 22 is 4.69
The square root of 75 is 8.66
The square root of 80 is 8.94
The square root of 28 is 5.29
The square root of 3 is 1.73
The square root of 33 is 5.74
The square root of 4 is 2.00
The square root of 81 is 9.00
The square root of 92 is 9.59
The square root of 43 is 6.56


In [20]:
matrix1 = np.random.randint(1, 15, size=(2, 3))

matrix2 = np.random.randint(15, 51, size=(3, 2))

matrix3 = np.random.randint(21, 31, size=(2, 2))


print(matrix1)
print("--------------------------------------")

print(matrix2)

print("--------------------------------------")

print(matrix3)

[[ 1 12 10]
 [ 7 12  9]]
--------------------------------------
[[19 27]
 [19 30]
 [28 42]]
--------------------------------------
[[23 25]
 [27 27]]


In [21]:
matrix1 = np.random.randint(1, 8, size=(2, 2))

matrix2 = np.random.randint(15, 26, size=(2, 2))

print(matrix1)
print("--------------------------------------")
print(matrix2)

[[3 3]
 [7 5]]
--------------------------------------
[[17 21]
 [15 21]]


In [22]:
scalar = 3
r_matrix1 = scalar * matrix1
r_matrix2 = scalar * matrix2

print(r_matrix1)
print("--------------------------------------")
print(r_matrix2)

[[ 9  9]
 [21 15]]
--------------------------------------
[[51 63]
 [45 63]]


In [23]:
# assignment
# 1) what happens when we transpose twice?

# >>>> it return to the original matrix
# ______________________________________________________________

# 2) confirm that the transpose operation work on non square matrices (rectangle matrices)

matrix2 = np.random.randint(15, 51, size=(5, 3))
print(matrix2)
print("------------------------------------------------------")
print(matrix2.T)

[[40 34 23]
 [33 19 32]
 [38 44 23]
 [23 40 27]
 [46 36 28]]
------------------------------------------------------
[[40 33 38 23 46]
 [34 19 44 40 36]
 [23 32 23 27 28]]


In [24]:
import numpy as np

matrix = np.random.randint(1, 10, size=(3, 3))

identity_matrix = np.identity(3)
zeros_matrix = np.zeros((3, 3))
transpose_matrix = matrix.T

identity = np.dot(matrix, identity_matrix)
zeros = np.dot(matrix, zeros_matrix)
transpose = np.dot(matrix, transpose_matrix)

print("Original Matrix:")
print(matrix)

print("\nIdentity Matrix:")
print(identity)

print("\nResult of Multiplying by Zeros Matrix:")
print(zeros)

print("\nResult of Multiplying by Transpose Matrix:")
print(transpose)


Original Matrix:
[[8 4 4]
 [3 2 8]
 [7 3 4]]

Identity Matrix:
[[8. 4. 4.]
 [3. 2. 8.]
 [7. 3. 4.]]

Result of Multiplying by Zeros Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Result of Multiplying by Transpose Matrix:
[[96 64 84]
 [64 77 59]
 [84 59 74]]


In [25]:

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

outer_product = np.outer(vector1, vector2)
print(outer_product)

cross_product = np.cross(vector1, vector2)
print("\nCross Product:")
print(cross_product)

matrix= np.random.rand(3, 3)  
inverse_matrix = np.linalg.inv(matrix)

print("\nOriginal 3x3 Matrix:")
print(matrix)

print("\nInverse Matrix:")
print(inverse_matrix)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]

Cross Product:
[-3  6 -3]

Original 3x3 Matrix:
[[0.62470467 0.97417406 0.58194106]
 [0.69470699 0.63624303 0.54016542]
 [0.24243828 0.6694873  0.06804873]]

Inverse Matrix:
[[-5.00931173  5.0875578   2.45414419]
 [ 1.31681734 -1.55114844  1.05169745]
 [ 4.89144234 -2.86477901 -4.39503567]]
